import { tcwgyd } from './tcwgyd.js'

describe('TCWGYD', () => {
  it('builds and exports the correct cards for the game', () => {
    expect(tcwgyd).toMatchInlineSnapshot(`
      {
        "players": {
          "max": 12,
          "min": 2,
        },
        "rounds": [
          [
            "Ask another player a true or false question about you. If they answer correctly you drink, otherwise they drink.",
            "Ask another player to confirm your guess of their underwear color you. If they show a different color you drink, otherwise they drink.",
            "Ask another player to have a staring contest with you. If they win you drink, otherwise they drink.",
            "Ask another player to play rock, paper, scissors with you. If they win you drink, otherwise they drink.",
            "Flip a coin. If it's heads, you drink, else, everyone else drinks.",
            "Keep it or donate it to someone. Free pass. Can be used once to get out of drinking.",
            "Keep it or donate it to someone. Free pass. Can be used once to get out of drinking.",
            "Keep it or donate it to someone. Free pass. Can be used once to get out of drinking.",
            "Keep it or donate it to someone. Free pass. Can be used once to get out of drinking.",
            "Keep it. Double attack. Can be used to once to force a drinker to drink a double.",
            "Keep it. Double attack. Can be used to once to force a drinker to drink a double.",
            "Keep it. Double attack. Can be used to once to force a drinker to drink a double.",
            "Keep it. Drinking buddies. Can be used to once to force someone else to drink with you.",
            "Keep it. Drinking buddies. Can be used to once to force someone else to drink with you.",
            "Keep it. Drinking buddies. Can be used to once to force someone else to drink with you.",
            "Keep it. Swap attack. Can be used to once to force someone else to drink instead of you.",
            "Keep it. Swap attack. Can be used to once to force someone else to drink instead of you.",
            "Keep it. Swap attack. Can be used to once to force someone else to drink instead of you.",
            "Make any action the next person repeats all previous ations and adds another. Continue until someone messes up. That person drinks.",
            "On the count of three, everyone hold up either a thumbs up or down. Whoever does opposite of you drinks.",
            "On the count of three, everyone is in a staring contest. Whoever last blinks picks someone drinks.",
            "On the count of three, everyone says a color of the rainbow. Whoever says the same as you drinks.",
            "Person(s) after you. The winners drink.",
            "Person(s) after you. The winners drink.",
            "Person(s) attracted to men. The winners drink.",
            "Person(s) attracted to women. The winners drink.",
            "Person(s) before you. The winners drink.",
            "Person(s) before you. The winners drink.",
            "Person(s) drank in the last round. The winners picks someone to drink.",
            "Person(s) have any dietary restriction. The winners drink.",
            "Person(s) longest first name. The winners drink.",
            "Person(s) most recently posted on instagram. The winners drink.",
            "Person(s) most recently used the bathroom. The winners drink.",
            "Person(s) older than you. The winners drink.",
            "Person(s) shortest last name. The winners drink.",
            "Person(s) single. The winners drink.",
            "Person(s) that clap their hands last. The winners drink.",
            "Person(s) that touch their nose last. The winners drink.",
            "Person(s) votes on who has the biggest hands. The winners picks someone to drink.",
            "Person(s) votes on who is the biggest alcoholic. The winners picks someone to drink.",
            "Person(s) votes on who is the biggest asshole. The winners drink.",
            "Person(s) votes on who is the most indecisive. The winners picks someone to drink.",
            "Person(s) votes on who is the most likely to argue with a stranger. The winners drink.",
            "Person(s) votes on who is the most likely to be in bed by 10PM. The winners drink.",
            "Person(s) votes on who is the most likely to dodge drinks. The winners drink.",
            "Person(s) votes on who is the most likely to get arrested. The winners drink.",
            "Person(s) votes on who is the most likely to get thrown out a bar. The winners drink.",
            "Person(s) votes on who is the most likely to own ten cats. The winners picks everyone else to drink.",
            "Person(s) votes on who is the most likely to spend money on something ridiculous. The winners drink.",
            "Person(s) votes on who is the most likely to yack. The winners picks everyone else to drink.",
            "Person(s) votes on who is the nicest. The winners picks someone to drink.",
            "Person(s) votes on who to drink. The winners drink.",
            "Person(s) wearing a shirt with buttons. The winners drink.",
            "Person(s) wearing a watch. The winners drink.",
            "Person(s) wearing glasses. The winners drink.",
            "Person(s) wearing jeans. The winners drink.",
            "Person(s) wearing same color shirt as you. The winners drink.",
            "Person(s) who are shorter than you. The winners drink.",
            "Person(s) who are taller than you. The winners drink.",
            "Person(s) who have longer hair than you. The winners drink.",
            "Person(s) with an android phone. The winners drink.",
            "Person(s) with an apple phone. The winners drink.",
            "Person(s) with the biggest ears. The winners drink.",
            "Person(s) with the smallest ears. The winners drink.",
            "Person(s) without touching anything balance on one leg and last one to fall wins. The winners picks someone to drink.",
            "Person(s) younger than you. The winners drink.",
            "Pick a animal and act out animal without talking/speaking/singing. First to guess correctly picks someone to drink. If no one guesses you drink.",
            "Pick a movie (scene) and act out movie (scene) without talking/speaking/singing. First to guess correctly picks someone to drink. If no one guesses you drink.",
            "Pick a song (melody) and act out song (melody) without talking/speaking/singing. First to guess correctly picks someone to drink. If no one guesses you drink.",
            "Pick a superhero and act out superhero without talking/speaking/singing. First to guess correctly picks someone to drink. If no one guesses you drink.",
            "Pick two people to perform a dance move of your choice. You pick the worse performer to drink.",
            "Pick two people to perform a song of your choice. You pick the worse performer to drink.",
            "Start with you, pick a animal and everyone takes turns saying different. First person to hesitate or repeat a animal drinks.",
            "Start with you, pick a beer brands and everyone takes turns saying different. First person to hesitate or repeat a beer brands drinks.",
            "Start with you, pick a color and everyone takes turns saying different. First person to hesitate or repeat a color drinks.",
            "Start with you, pick a fruit and everyone takes turns saying different. First person to hesitate or repeat a fruit drinks.",
            "Start with you, pick a human organ and everyone takes turns saying different. First person to hesitate or repeat a human organ drinks.",
            "Start with you, pick a ocean animal and everyone takes turns saying different. First person to hesitate or repeat a ocean animal drinks.",
            "Start with you, pick a spice and everyone takes turns saying different. First person to hesitate or repeat a spice drinks.",
            "Start with you, pick a word and everyone takes turns saying rhyming. First person to hesitate or repeat a word drinks.",
            "Tell a joke. If no one chuckles or laughs, you drink.",
            "Tell two truths and a lie. If the first person to guess picks the lie, you drink otherwise they drink.",
            "Until it's your turn, everyone has to follow a rule you make up. All rule breaker(s) drink.",
            "Until it's your turn, everyone has to follow a rule you make up. All rule breaker(s) drink.",
            "Until it's your turn, everyone must play in silence. First rule breaker(s) drink.",
            "Until it's your turn, everyone speaks in the third person. First rule breaker(s) drink.",
            "Until it's your turn, everyone speaks with one syllable words. First rule breaker(s) drink.",
            "Until it's your turn, you are "Simon", everyone plays "Simon Says". First rule breaker(s) drink.",
            "Until it's your turn, you can not laugh. First rule breaker(s) drink.",
            "Until it's your turn, you can not make eye contact with anyone. First rule breaker(s) drink.",
            "Until it's your turn, you can not open your eyes. First rule breaker(s) drink.",
            "You can either answer truthfully any question the person after you asks or refuse and drink.",
            "You can either fulfill succesfully any action the person after you dares or refuse and drink.",
            "You can either switch shirts with someone for the remainder of the game or refuse and drink.",
            "You can either take off an article of clothing, including neither accessory nor jewelry or refuse and drink.",
            "You drink.",
            "You drink.",
            "You drink.",
            "You drink.",
            "You drink.",
          ],
        ],
        "title": "These Cards Will Get You Drunk",
      }
    `)
  })
})
